### ISSUE TITLE
Feature: inline test-data-id

### ISSUE THREAD

**Issue by dschinkel** [davidmfoley/isolate-components#17]
I would like to be able to do this for example:
`const image = company.inline("[data-test-id=company-header-image]");`
or better
`const image = company.inline.testId("company-header-image");`
or 
`const image = company.inline.findTestId("company-header-image");`

You might wanna base it on `data-testId` to make it easier for people to ditch RTL and start using something better! 🙃

```
	it("shows company header image", () => {
          const imageUrl = "abc";

	  const company = isolateComponent(<Router><Company imageUrl={imageUrl} /></Router>);
	  const image = company.inline("[data-test-id=company-header-image]");

	  expect(image.props.src).to.equal(imageUrl);
	});
```

**Comment by davidmfoley** [comment]
The purpose of `inline` is to render a react component.

In your example you are isolating the `Router` component, so `Company` is not being rendered, so what I think you need to do is to inline `Company`.

I think this might do it:
```js
	it("shows company header image", () => {
          const imageUrl = "abc";

	  const company = isolateComponent(<Router><Company imageUrl={imageUrl} /></Router>);
          company.inline(Company); // render the Company component
	  const image = company.findOne("[data-test-id=company-header-image]");

	  expect(image.props.src).to.equal(imageUrl);
	});
```

**Comment by dschinkel** [comment]
Still working on it, now a problem, now with react-router `match`.  

I think the **inline** is losing the Router that was initially wrapping the component?

```js
import { Route, MemoryRouter as Router } from 'react-router-dom';

it('shows company header image', () => {
  const imageUrl = 'abc';
  const companyStub = { ...stubCompanyNew };
  const fetchCompanyNewStub = async () => companyStub;

  const company = isolateComponent(
    <Router initialEntries={['/companies/0/interview']}>
      <Route path="/companies/:companyId/interview">
        <CompanyNew imageUrl={imageUrl} fetchCompanyNew={fetchCompanyNewStub} />
      </Route>
    </Router>
  );

  company.inline(CompanyNew);
  const image = company.findOne('[data-test-id=company-header-image]');

  expect(image.props.src).to.equal(imageUrl);
});
```

**Error**
```js
TypeError: Cannot read property 'match' of undefined
      at Object.useParams (node_modules/react-router/modules/hooks.js:40:17)
      at CompanyNew (views/CompanyNew/companyNew.tsx:13:24)
      at /Users/daveschinkel/code/projects/we-do-tdd/src/client/node_modules/isolate-components/lib/isolatedRenderer/index.js:27:28
      at invokeHook (node_modules/isolate-hooks/lib/index.js:38:26)
      at Object.render (node_modules/isolate-components/lib/isolatedRenderer/index.js:33:9)
      at /Users/daveschinkel/code/projects/we-do-tdd/src/client/node_modules/isolate-components/lib/nodeTree/inline.js:16:43
      at Array.forEach (<anonymous>)
      at Object.doInline (node_modules/isolate-components/lib/nodeTree/inline.js:14:23)
      at /Users/daveschinkel/code/projects/we-do-tdd/src/client/node_modules/isolate-components/lib/nodeTree/inline.js:20:21
      at Array.forEach (<anonymous>)
      at Object.doInline (node_modules/isolate-components/lib/nodeTree/inline.js:14:23)
      at Object.inlineAll (node_modules/isolate-components/lib/nodeTree/index.js:32:29)
      at Object.inlineAll (node_modules/isolate-components/lib/isolatedRenderer/index.js:52:22)
      at Object.inline (node_modules/isolate-components/lib/isolateComponent.js:19:40)
      at Context.<anonymous> (test/UseCases/Company/component/show.company.header.spec.tsx:22:11)
```

**CompanyNew.tsx**
```js
import { useParams } from 'react-router-dom';

interface CompanyNewProps {
  imageUrl: string;
}

export function CompanyNew(props: CompanyNewProps) {
  const { companyId } = useParams<{ companyId: string }>();
  const [company, setCompany] = useState<CompanyModel>();

  useEffect(() => {
    const getCompany = async () => {
    const company = await Company().fetchCompanyNew(companyId);
      setCompany(company);
    };
    getCompany();
  }, []);

  return (
    <>
      <img alt="Company Header Image" data-test-id="company-header-image" src={props.imageUrl} />
      <CompanyDetail className="ft-company-detail" company={company} />
    </>
  );
}
```

An equivalent test with RTL that does pass (when changing prod to `data-testid` of course):
```js
import { MemoryRouter as Router } from 'react-router-dom';

it('shows company header image', () => {
  const companyStub = { ...stubCompanyNew };
  const imageUrl = (companyStub.profile.header.imageUrl = 'abc');
  const fetchCompanyNewStub = async () => companyStub;

  const company = render(
    <Router>
       <CompanyNew imageUrl={imageUrl} fetchCompanyNew={fetchCompanyNewStub} />
    </Router>,
  );
  
  const image = company.getByTestId('company-header-image');

  expect(image.getAttribute('src')).to.equal(imageUrl);
});
```

**Comment by davidmfoley** [comment]
@dschinkel Just added support for older-style Context.Consumers (used internally by react-router). Version 1.3.1 and later should support the use case of testing with a MemoryRouter and nested Routes. [See this test for a react-router example](https://github.com/davidmfoley/isolate-components/blob/master/test/react_router_route_matching_test.tsx)
