### ISSUE TITLE
Request: Support function components wrapped in memo

### ISSUE THREAD

**Issue by kyelewis** [davidmfoley/isolate-components#19]
Want to say, this library is great.. maybe i'll find time to dive in and try to work this out myself, but if not:

Inlining function components wrapped in memo() returns this error:

```
    TypeError: renderMethod is not a function

      at node_modules/isolate-components/lib/isolatedRenderer/index.js:27:28
      at render (node_modules/isolate-hooks/lib/index.js:38:40)
      at Object.render (node_modules/isolate-components/lib/isolatedRenderer/index.js:33:9)
      at forEach (node_modules/isolate-components/lib/nodeTree/inline.js:16:43)
          at Array.forEach (<anonymous>)
      at Object.doInline (node_modules/isolate-components/lib/nodeTree/inline.js:14:23)
      at forEach (node_modules/isolate-components/lib/nodeTree/inline.js:20:21)
          at Array.forEach (<anonymous>)
      at Object.doInline (node_modules/isolate-components/lib/nodeTree/inline.js:14:23)
      at node_modules/isolate-components/lib/nodeTree/inline.js:20:21
```

When not inlining, they appear as <undefined ...> in toString() output.

It'd be great to support them if it's a simple thing!

isolate-components v1.1.3, react 17, react-native

**Comment by davidmfoley** [comment]
thanks for the report; I made a quick workaround in 1.1.4 and will fix this for real later -- note that in 1.1.4 no memoization actually occurs (it is rendered each time, regardless of props) -- see the tests here https://github.com/davidmfoley/isolate-components/commit/5482de91ba8b92601d8f0d9ffd7fe3d2b9941c6f#diff-7cf99adf8ee22020366a84d2a751bccf8fc3e43029c9df2e7c75b2d72c8213d0 (note the skipped test as well)

**Comment by kyelewis** [comment]
Thanks @davidmfoley for the fast turnaround!

**Comment by davidmfoley** [comment]
Added React.memo support "for real" in v1.4.0
