### ISSUE TITLE
Feature Request: Handle Case When Render returns Null

### ISSUE THREAD

**Issue by dschinkel** [davidmfoley/isolate-components#7]
**Sad Path Test:**

```js
it('does not show location tag', () => {
  const company = {...companyStub}
  company.showLocation = false;

  const companyLocation = isolateComponent(<CompanyLocationTag company={company} />);

  expect(companyLocation).to.be.null;
});
```

**CompanyLocationTag**
```js
export function CompanyLocationTag({ company }: { company: Company}) {
  return company.showLocation && <SolidTagLink color="orange" href="" text="location" toolTipText="location" />
  || null;
}
```

Here I expect my React hook to render nothing when showLocation is false however shallow render seems to fail on the case where a React component does not render anything.

Stack Trace:
```
TypeError: Cannot read property 'props' of null
    at parse (node_modules/isolate-components/lib/nodeTree.js:37:21)
    at Object.exports.nodeTree (node_modules/isolate-components/lib/nodeTree.js:48:18)
    at /Users/coffeegrinds/code/other/projects/we-do-tdd/node_modules/isolate-components/lib/index.js:31:27
    at invokeHook (node_modules/isolate-hooks/lib/index.js:24:26)
    at Object.exports.isolateComponent (node_modules/isolate-components/lib/index.js:33:5)
    at Context.<anonymous> (src/test/client/unit/usecases/list.featured.companies.spec.tsx:38:29)
```

**Comment by davidmfoley** [comment]
This is fixed in 0.1.4 -- note that rather than: 


`expect(companyLocation).to.be.null;`

you will want to do:

`expect(companyLocation.content()).to.be.null;`

This is so that you can subsequently set props or trigger effects on the component under test.
